package principal;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivi
 */
public class Principal extends javax.swing.JFrame {

    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connection miConexion=Utilidades.conexionBD();

        DefaultTableModel modelo=new DefaultTableModel();
        Utilidades.resultadoEnTabla(miConexion, modelo);
        tablaMusicos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMusicos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMusicos = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        panelAniadirMusico = new javax.swing.JPanel();
        txtIdNuevo = new javax.swing.JTextField();
        txtNombreNuevo = new javax.swing.JTextField();
        txtApellidosNuevo = new javax.swing.JTextField();
        txtDireccionNuevo = new javax.swing.JTextField();
        btnAniadir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelEliminarMusico = new javax.swing.JPanel();
        panelMusicos1 = new javax.swing.JPanel();
        txtIdEliminar = new javax.swing.JTextField();
        txtNombreEliminar = new javax.swing.JTextField();
        txtApellidosEliminar = new javax.swing.JTextField();
        txtDireccionEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado Músicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tablaMusicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMusicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMusicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMusicos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelMusicosLayout = new javax.swing.GroupLayout(panelMusicos);
        panelMusicos.setLayout(panelMusicosLayout);
        panelMusicosLayout.setHorizontalGroup(
            panelMusicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelMusicosLayout.setVerticalGroup(
            panelMusicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelMusicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Músicos", panelMusicos);

        btnAniadir.setText("Añadir");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAniadirMusicoLayout = new javax.swing.GroupLayout(panelAniadirMusico);
        panelAniadirMusico.setLayout(panelAniadirMusicoLayout);
        panelAniadirMusicoLayout.setHorizontalGroup(
            panelAniadirMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAniadirMusicoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelAniadirMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAniadirMusicoLayout.createSequentialGroup()
                        .addComponent(btnAniadir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addGroup(panelAniadirMusicoLayout.createSequentialGroup()
                        .addComponent(txtIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidosNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelAniadirMusicoLayout.setVerticalGroup(
            panelAniadirMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAniadirMusicoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(panelAniadirMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAniadirMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAniadir)
                    .addComponent(btnLimpiar))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Añadir Músico", panelAniadirMusico);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMusicos1Layout = new javax.swing.GroupLayout(panelMusicos1);
        panelMusicos1.setLayout(panelMusicos1Layout);
        panelMusicos1Layout.setHorizontalGroup(
            panelMusicos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicos1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMusicos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addGroup(panelMusicos1Layout.createSequentialGroup()
                        .addComponent(txtIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelMusicos1Layout.setVerticalGroup(
            panelMusicos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicos1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelMusicos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelEliminarMusicoLayout = new javax.swing.GroupLayout(panelEliminarMusico);
        panelEliminarMusico.setLayout(panelEliminarMusicoLayout);
        panelEliminarMusicoLayout.setHorizontalGroup(
            panelEliminarMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(panelEliminarMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminarMusicoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMusicos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelEliminarMusicoLayout.setVerticalGroup(
            panelEliminarMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
            .addGroup(panelEliminarMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminarMusicoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMusicos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Eliminar Músico", panelEliminarMusico);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMusicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMusicosMouseClicked
        int indice=tablaMusicos.getSelectedRow();
        
        txtId.setText(tablaMusicos.getValueAt(indice,0).toString());
        txtIdEliminar.setText(tablaMusicos.getValueAt(indice,0).toString());
        txtNombre.setText(tablaMusicos.getValueAt(indice,1).toString());
        txtNombreEliminar.setText(tablaMusicos.getValueAt(indice,1).toString());
        txtApellidos.setText(tablaMusicos.getValueAt(indice,2).toString());
        txtApellidosEliminar.setText(tablaMusicos.getValueAt(indice,2).toString());
        txtDireccion.setText(tablaMusicos.getValueAt(indice,3).toString());
        txtDireccionEliminar.setText(tablaMusicos.getValueAt(indice,3).toString());
    }//GEN-LAST:event_tablaMusicosMouseClicked

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        Connection miConexion=Utilidades.conexionBD();
        int id=0;
        boolean cid=true;
        try{
            id=Integer.parseInt(txtIdNuevo.getText());
            cid=Utilidades.comprobarID(miConexion, id);
            if(cid==false){
                JOptionPane.showMessageDialog(null, "El ID ingresado ya está en uso\nIngresa un ID válido", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Id del Músico incorrecto!!!", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
        String nombre=txtNombreNuevo.getText();
        String apell=txtApellidosNuevo.getText();
        String direc=txtDireccionNuevo.getText();
        if(!(nombre.equals(""))&&!(apell.equals(""))&&!(direc.equals(""))&&(cid==true)){
            Utilidades.aniadir(miConexion,id,nombre,apell,direc);

            DefaultTableModel modelo=new DefaultTableModel();
            Utilidades.resultadoEnTabla(miConexion, modelo);
            tablaMusicos.setModel(modelo);

            txtIdNuevo.setText("");
            txtNombreNuevo.setText("");
            txtApellidosNuevo.setText("");
            txtDireccionNuevo.setText("");
            txtDireccionNuevo.setText("");
        }else if(cid==true){
            JOptionPane.showMessageDialog(this, "Todos los datos son obligatorios\n Revisa los datos!!!", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdNuevo.setText("");
        txtNombreNuevo.setText("");
        txtApellidosNuevo.setText("");
        txtDireccionNuevo.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Connection miConexion=Utilidades.conexionBD();
        
        if(tablaMusicos.getSelectedRow()!=-1){
            int id=Integer.parseInt(txtIdEliminar.getText());
            int dialogo=JOptionPane.showConfirmDialog(this, "¿Realmente desea eliminar este Músico?", "Comfirmación", JOptionPane.YES_NO_OPTION);
            if(dialogo==0){
                Utilidades.eliminarMusico(miConexion, id);

                DefaultTableModel modelo=new DefaultTableModel();
                Utilidades.resultadoEnTabla(miConexion, modelo);
                tablaMusicos.setModel(modelo);
                txtIdEliminar.setText("");
                txtNombreEliminar.setText("");
                txtApellidosEliminar.setText("");
                txtDireccionEliminar.setText("");
            }
        } else{
            JOptionPane.showMessageDialog(this, "Selecciona el Músico a borrar primero!!!", "Información", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex()==0){
            txtId.setEditable(false);
            txtNombre.setEditable(false);
            txtApellidos.setEditable(false);
            txtDireccion.setEditable(false);
        }
        if(jTabbedPane1.getSelectedIndex()==0){
            txtIdEliminar.setEditable(false);
            txtNombreEliminar.setEditable(false);
            txtApellidosEliminar.setEditable(false);
            txtDireccionEliminar.setEditable(false);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelAniadirMusico;
    private javax.swing.JPanel panelEliminarMusico;
    private javax.swing.JPanel panelMusicos;
    private javax.swing.JPanel panelMusicos1;
    private javax.swing.JTable tablaMusicos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidosEliminar;
    private javax.swing.JTextField txtApellidosNuevo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEliminar;
    private javax.swing.JTextField txtDireccionNuevo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEliminar;
    private javax.swing.JTextField txtIdNuevo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEliminar;
    private javax.swing.JTextField txtNombreNuevo;
    // End of variables declaration//GEN-END:variables
}
